from copy import deepcopy

from .paths import DATA_ROOT


DATASET_CONFIGS = {
    "aqua20_clip": {
        "name": "AQUA20 CLIP Features",
        "num_classes": 20,
        "feature_dataset": True,
        "feature_dim": 512,
        "hidden_dim": 512,
        "batch_size": 256,
        "epochs": 100,
        "lr": 1e-3,
        "weight_decay": 0.01,
        "label_smoothing": 0.05,
        "warmup_epochs": 5,
        "dropout": 0.2,
        "balanced_sampling": "sqrt",
        "early_stopping_patience": 20,
        "num_workers": 0,
        "data_dir": f"{DATA_ROOT}/aqua20_clip_features",
    },
    "aqua20_clip_spatial": {
        "name": "AQUA20 CLIP Spatial SpyMamba",
        "num_classes": 20,
        "feature_dataset": True,
        "spatial_feature_dataset": True,
        "feature_dim": 768,
        "feature_height": 14,
        "feature_width": 14,
        "patch_size": 2,
        "model_dim": 128,
        "depth": 6,
        "batch_size": 128,
        "epochs": 20,
        "lr": 3e-4,
        "weight_decay": 0.05,
        "label_smoothing": 0.1,
        "warmup_epochs": 5,
        "stochastic_depth": 0.0,
        "dropout": 0.0,
        "balanced_sampling": None,
        "early_stopping_patience": None,
        "num_workers": 0,
        "data_dir": f"{DATA_ROOT}/aqua20_clip_vit_b16_spatial_grid_aug",
    },
    "aqua20": {
        "name": "AQUA20",
        "num_classes": 20,
        # AQUA20 images are distributed at/around 225 px. 224 gives a clean
        # 28x28 token grid with an 8x8 patch embedding.
        "img_size": 224,
        "patch_size": 8,
        "channels": 3,
        "mean": (0.485, 0.456, 0.406),
        "std": (0.229, 0.224, 0.225),
        "batch_size": 64,
        "epochs": 150,
        "lr": 3e-4,
        "weight_decay": 0.05,
        "label_smoothing": 0.1,
        "mixup_alpha": 0.8,
        "cutmix_alpha": 1.0,
        "mix_probability": 0.5,
        "warmup_epochs": 5,
        "stochastic_depth": 0.1,
        "randaugment": True,
        "repeated_aug": False,
        # Square-root inverse-frequency sampling moderates AQUA20's extreme
        # imbalance without oversampling the rarest classes as aggressively
        # as fully class-uniform sampling.
        "balanced_sampling": "sqrt",
        "early_stopping_patience": 30,
        "freeze_first_blocks_on_transfer": 5,
        "random_erasing": 0.25,
        "resize_size": 256,
        "data_dir": f"{DATA_ROOT}/aqua20",
    },
    "fathomnet_pretrain": {
        "name": "FathomNet Pretrain",
        "num_classes": 60,
        "img_size": 224,
        "patch_size": 8,
        "channels": 3,
        "mean": (0.485, 0.456, 0.406),
        "std": (0.229, 0.224, 0.225),
        "batch_size": 64,
        "epochs": 100,
        "lr": 3e-4,
        "weight_decay": 0.05,
        "label_smoothing": 0.1,
        "mixup_alpha": 0.8,
        "cutmix_alpha": 1.0,
        "mix_probability": 0.5,
        "warmup_epochs": 5,
        "stochastic_depth": 0.1,
        "randaugment": True,
        "repeated_aug": False,
        "random_erasing": 0.25,
        "resize_size": 256,
        "data_dir": f"{DATA_ROOT}/fathomnet_pretrain",
    },
    "cifar10": {
        "name": "CIFAR-10",
        "num_classes": 10,
        "img_size": 32,
        "channels": 3,
        "mean": (0.4914, 0.4822, 0.4465),
        "std": (0.2470, 0.2435, 0.2616),
        "batch_size": 256,
        "epochs": 300,
        "lr": 1e-3,
        "weight_decay": 0.05,
        "label_smoothing": 0.1,
        "mixup_alpha": 0.8,
        "cutmix_alpha": 1.0,
        "warmup_epochs": 10,
        "stochastic_depth": 0.1,
        "randaugment": True,
        "repeated_aug": True,
        "random_erasing": 0.25,
    },
    "cifar100": {
        "name": "CIFAR-100",
        "num_classes": 100,
        "img_size": 32,
        "channels": 3,
        "mean": (0.5071, 0.4865, 0.4409),
        "std": (0.2673, 0.2564, 0.2762),
        "batch_size": 256,
        "epochs": 300,
        "lr": 1e-3,
        "weight_decay": 0.05,
        "label_smoothing": 0.1,
        "mixup_alpha": 0.8,
        "cutmix_alpha": 1.0,
        "warmup_epochs": 10,
        "stochastic_depth": 0.1,
        "randaugment": True,
        "repeated_aug": True,
        "random_erasing": 0.25,
    },
    "tiny_imagenet": {
        "name": "Tiny ImageNet",
        "num_classes": 200,
        "img_size": 64,
        "channels": 3,
        "mean": (0.4802, 0.4481, 0.3975),
        "std": (0.2302, 0.2265, 0.2262),
        "batch_size": 256,
        "epochs": 300,
        "lr": 1e-3,
        "weight_decay": 0.05,
        "label_smoothing": 0.1,
        "mixup_alpha": 0.8,
        "cutmix_alpha": 1.0,
        "warmup_epochs": 10,
        "stochastic_depth": 0.1,
        "randaugment": True,
        "repeated_aug": True,
        "random_erasing": 0.25,
        "data_dir": f"{DATA_ROOT}/tiny-imagenet-200",
    },
}

DEFAULT_DATASETS_TO_RUN = ["aqua20_clip"]
RUN_SEED = 42


def get_dataset_config(name):
    if name not in DATASET_CONFIGS:
        raise ValueError(f"Unknown dataset config: {name}")
    return deepcopy(DATASET_CONFIGS[name])
